const VALID_TURNS = ['KAMEN', 'PAPIER', 'NOZNICE', 'error'];
const TURN_EMOJI = new Map([['KAMEN', '🪨'], ['PAPIER', '📄'], ['NOZNICE', '✂️'], ['error', '⚠️']]);
let TURN_NUMBER_ELEMENTS: HTMLButtonElement[] = [];
let TURN_PAIR_ELEMENTS: Array<[HTMLParagraphElement, HTMLParagraphElement]> = [];
let CURRENT_TURN_ELEMENTS: [HTMLParagraphElement|null, HTMLParagraphElement|null] = [null, null];
let CURRENT_TURN_RESULT_TEXT_ELEMENTS: [HTMLParagraphElement|null, HTMLParagraphElement|null] = [null, null];
let CURRENT_TURN = -1;
let SPEED = 1;
let PAUSED = true;
let PLAYER_NAMES: (string|null)[] = [null, null];
let GAME_TURNS: string[][] = [];
let FINAL_SCORE: (string|null)[] = [null, null]
let ERROR_MSG = '';
let ANIMATION_IS_PAUSED = true;
let ANIMATION_SPEED = 1;
let CURRENT_ANIMATION_UUID: string|null = null;
const WAIT_BETWEEN_TURN_ANIMATION = 2000;
// let ANIMATING_TOWARDS_TURN: number|null = null;
const WINNER_COLOR = '#00ff00'
const LOSER_COLOR = '#ff0000'
const DRAW_COLOR = '#ffb700'

function init() {
    let fileSelector = document.getElementById('upload_input');
    if (!fileSelector){return;}
    fileSelector.addEventListener('change', (event)=>{
        console.log('Detected file, upload, running handle_upload()')
        // @ts-ignore
        handle_upload(event.target?.files[0]);
    })
}

function handle_upload(file: File){
    console.log(`File upload: ${file.name}`)
    const reader = new FileReader();
    reader.readAsText(file);
    reader.addEventListener('load', (e) => {
        // @ts-ignore
        loadGameData(e.target.result.split('\n'))
    })
}

function validateTurn(turn: string){
    return VALID_TURNS.indexOf(turn) != -1;
}

function parseGameData(data: string[]){
    console.log(`Parsing game data...`)
    // console.log(`DEBUG LOG!`)
    if (!Array.isArray(data)){
        ERROR_MSG = `Error in parseGameData(): data argument must an array.`
        return null;
    }
    if (data.length < 3) {
        ERROR_MSG = `Game data too short, requires at least 3 lines.`
        return null;
    }

    // PLAYER NAMES
    PLAYER_NAMES[0] = data[0];
    PLAYER_NAMES[1] = data[1];

    // SCORE
    let score = data[2].split(' ');
    if (score.length != 2){
        ERROR_MSG = `Invalid score: Line 3 should contain two numbers, scores of players, got ${score}.`
        return null;
    }
    if (isNaN(Number.parseInt(score[0]))){
        ERROR_MSG = `Invalid score: Line 3 should contain two numbers, ${score[0]} is not a number.`
        return null;
    }
    if (isNaN(Number.parseInt(score[1]))){
        ERROR_MSG = `Invalid score: Line 3 should contain two numbers, ${score[1]} is not a number.`
        return null;
    }
    FINAL_SCORE = score;

    // TURNS
    GAME_TURNS = [];
    for (let i = 3; i < data.length; i++) {
        let line = data[i].split(" ");
        if (line.length != 2) {
            if (line.length < 2) {
                ERROR_MSG = `Invalid data structure on line ${i}: Too little turns, requires 2, got ${line.length}`;
            } else {
                ERROR_MSG = `Invalid data structure on line ${i}: Too many turns, requires 2, got ${line.length}`;
            }
            return null;
        }
        if (!validateTurn(line[0])){
            ERROR_MSG = `Invalid turn '${line[0]}' on line ${i}`
            return null;
        }
        if (!validateTurn(line[1])){
            ERROR_MSG = `Invalid turn '${line[1]}' on line ${i}`
            return null;
        }
        GAME_TURNS.push(line);
    }
    CURRENT_TURN = 0;
    // console.log(`Done parsing data.`)
    return true;
}

function loadGameData(data: string[]){
    const result: (boolean|null) = parseGameData(data);
    // console.log(`Parsedata returned: ${result}`)
    if (result == null){
        alert(`Error parsing game data: ${ERROR_MSG}.`)
    } else {
        console.log(`Loaded succesfully!`)
    }
    document.getElementById("upload_div")!.style.display = 'none';
    setupTurnReplay(GAME_TURNS);
}

// console.log(parseGameData(
//     ['player1', 'player2', '0 0', 'KAMEN KAMEN']
// )&&'[DEBUG] Successfully parsed!')
// console.log(`[DEBUG] PLAYER_NAMES=${PLAYER_NAMES} GAME_TURNS=${GAME_TURNS}`)

function whoWonMatch(turn1: string, turn2: string) {
    if (!VALID_TURNS.includes(turn1) || !VALID_TURNS.includes(turn2)){
        return 0;
    }

    // Rest of function was generated by Gemini 3.6 Flash
    if (turn1 === turn2) return 0;
    if (turn1 === "error") return 2;
    if (turn2 === "error") return 1;

    const WINNING_MOVES: Record<string, string> = {
        "KAMEN": "NOZNICE",
        "PAPIER": "KAMEN",
        "NOZNICE": "PAPIER"
    };

    return WINNING_MOVES[turn1] === turn2 ? 1 : 2;
}

function setupTurnReplay(turns: string[][]){
    document.getElementById("controls")!.style.display = 'block';
    document.getElementById("replay_canvas")!.style.display = 'grid';
    document.getElementById("replay_speed_input")!.addEventListener('input', (event)=>{
        // @ts-ignore
        setReplaySpeed(event.target.value);
    })
    setReplaySpeed(1);

    const current_turn_result_element1 = document.getElementById("current_turn_result_text_p1");
    const current_turn_result_element2 = document.getElementById("current_turn_result_text_p2");
    CURRENT_TURN_RESULT_TEXT_ELEMENTS = [
        current_turn_result_element1 instanceof HTMLParagraphElement ? current_turn_result_element1 : null,
        current_turn_result_element2 instanceof HTMLParagraphElement ? current_turn_result_element2 : null,
    ];

    const current_turn_element1 = document.getElementById("current_turn_p1_text");
    const current_turn_element2 = document.getElementById("current_turn_p2_text");
    CURRENT_TURN_ELEMENTS = [
        current_turn_element1 instanceof HTMLParagraphElement ? current_turn_element1 : null,
        current_turn_element2 instanceof HTMLParagraphElement ? current_turn_element2 : null,
    ];

    let turn_counter = document.getElementById("history_turn_counter")
    let history_p1 = document.getElementById("p1_history");
    let history_p2 = document.getElementById("p2_history");
    turns.forEach(
        (turn, index) => {
            const turn_number_element = document.createElement('button');
            turn_number_element.innerText = index.toString();
            turn_number_element.onclick = () => {changeTurn(index)};
            turn_counter?.appendChild(turn_number_element);
            TURN_NUMBER_ELEMENTS.push(turn_number_element);

            const winner = whoWonMatch(turn[0], turn[1]);

            const element1 = document.createElement('div');
            const element_text1 = document.createElement('p');
            const emoji1 = TURN_EMOJI.get(turn[0]) ?? 'ERROR LOADING EMOJI';
            element_text1.innerText = emoji1;
            element1.style.backgroundColor = [DRAW_COLOR, WINNER_COLOR, LOSER_COLOR][winner];
            element1.appendChild(element_text1);
            history_p1?.appendChild(element1);
            
            const element2 = document.createElement('div');
            const element_text2 = document.createElement('p');
            const emoji2 = TURN_EMOJI.get(turn[1]) ?? 'ERROR LOADING EMOJI';
            element_text2.innerText = emoji2;
            element2.style.backgroundColor = [DRAW_COLOR, LOSER_COLOR, WINNER_COLOR][winner];
            element2.appendChild(element_text2);
            history_p2?.appendChild(element2);
            TURN_PAIR_ELEMENTS.push([element1, element2]);
        }
    )
    changeTurn(0);
}

function game_controls_action(action: string){
    switch (action) {
        case 'pause':
            
            break;
    
        default:
            break;
    }
}

function isScrolledIntoView(elem: HTMLElement): boolean {
    const elemRect = elem.getBoundingClientRect();
    const container = document.getElementById("replay_canvas_history");
    if (!container) {
        console.error(`Failed to load replay_canvas_history`); return false;
    }
    const containerRect = container.getBoundingClientRect();

    return (
        elemRect.top >= containerRect.top &&
        elemRect.bottom <= containerRect.bottom &&
        elemRect.left >= containerRect.left &&
        elemRect.right <= containerRect.right
    );
}

function _focusScrollOnTurn(turn: number): void {
    if (turn < 0 || turn >= TURN_NUMBER_ELEMENTS.length) {
        return;
    }
    TURN_NUMBER_ELEMENTS[turn].scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'start' });
}

function _unfocusTurnInHistory(turn: number) {
    if (turn < 0 || turn >= TURN_NUMBER_ELEMENTS.length) { 
        return; 
    }

    const turn_number_element = TURN_NUMBER_ELEMENTS[turn];
    turn_number_element.style.backgroundColor = 'black';
    turn_number_element.style.color = 'white';
}

function _focusTurnInHistory(turn: number) {
    if (turn < 0 || turn >= GAME_TURNS.length) { return; }
    const turn_number_element = TURN_NUMBER_ELEMENTS[turn];
    turn_number_element.style.backgroundColor = 'yellow';
    turn_number_element.style.color = 'black';
}

function changeTurn(turn: number) {
    console.log(`FOCUS TURN ${turn}`);
    _unfocusTurnInHistory(CURRENT_TURN);
    _focusTurnInHistory(turn);
    // if (ANIMATING_TOWARDS_TURN) {
    //     _unfocusTurnInHistory(ANIMATING_TOWARDS_TURN);
    // }

    if (turn < 0 || turn >= TURN_NUMBER_ELEMENTS.length) { 
        return; 
    }
    CURRENT_TURN = turn;


    if (turn < 0 || turn >= GAME_TURNS.length) { return; }

    // console.log(`CURRENT_TURN_ELEMENTS: ${CURRENT_TURN_ELEMENTS[0]?.textContent}`)
    // if (CURRENT_TURN_ELEMENTS[0]){
    //     CURRENT_TURN_ELEMENTS[0].textContent = TURN_EMOJI.get(GAME_TURNS[turn][0]) ?? "Error";
    //     // console.log(`Set emoji to ${TURN_EMOJI.get(GAME_TURNS[turn][0]) ?? "Error"}`)
    // } else {console.log(`Coundn't find current turn element 0`)} 
    
    // if (CURRENT_TURN_ELEMENTS[1]){
    //     CURRENT_TURN_ELEMENTS[1].textContent = TURN_EMOJI.get(GAME_TURNS[turn][1]) ?? "Error";
    // } else {console.log(`Coundn't find current turn element 1`)} 

    const winner = whoWonMatch(GAME_TURNS[turn][0], GAME_TURNS[turn][1]);
    if (!CURRENT_TURN_RESULT_TEXT_ELEMENTS[0] || !CURRENT_TURN_RESULT_TEXT_ELEMENTS[1]) { console.error(`Current turn elements not loaded.`); return; }
    CURRENT_TURN_RESULT_TEXT_ELEMENTS[0].textContent = ['DRAW', 'WINNER', 'LOSER'][winner];
    CURRENT_TURN_RESULT_TEXT_ELEMENTS[1].textContent = ['DRAW', 'LOSER', 'WINNER'][winner];

    if (!CURRENT_TURN_ELEMENTS[0] || !CURRENT_TURN_ELEMENTS[1]) { console.error(`Current turn elements not loaded.`); return; }
    CURRENT_TURN_ELEMENTS[0].textContent = TURN_EMOJI.get(GAME_TURNS[turn][0]) ?? GAME_TURNS[turn][0];
    CURRENT_TURN_ELEMENTS[0].style.backgroundColor = [DRAW_COLOR, WINNER_COLOR, LOSER_COLOR][winner];
    CURRENT_TURN_ELEMENTS[1].textContent = TURN_EMOJI.get(GAME_TURNS[turn][1]) ?? GAME_TURNS[turn][1];
    CURRENT_TURN_ELEMENTS[1].style.backgroundColor = [DRAW_COLOR, LOSER_COLOR, WINNER_COLOR][winner];

    _focusScrollOnTurn(turn);    
}

function cancelCurrentAnimation(pause_replay?:boolean) {
    if (pause_replay) {
        document.getElementById("pause_button")!.textContent = "Resume";
        ANIMATION_IS_PAUSED = true;
    }
    changeTurn(CURRENT_TURN);
    CURRENT_ANIMATION_UUID = null;
}

function nextTurn(){
    console.log(`FOCUS_NEXT`);
    if (CURRENT_TURN >= TURN_NUMBER_ELEMENTS.length-1) {
        return;
    }
    cancelCurrentAnimation(true);
    changeTurn(CURRENT_TURN + 1);
}

function previousTurn(){
    console.log(`FOCUS_PREVIOUS`);
    if (CURRENT_TURN <= 0) {
        return;
    }
    cancelCurrentAnimation(true);
    changeTurn(CURRENT_TURN - 1);
}

function DEBUGisinview(){
    console.log(`Is in view? ${isScrolledIntoView(TURN_NUMBER_ELEMENTS[17])} ${TURN_NUMBER_ELEMENTS[17].innerText}`);
}

function animateTurn(turn?: number, countDownTickTime?: number) {
    function setBothTurnResultElementsTo(text: string) {
        CURRENT_TURN_RESULT_TEXT_ELEMENTS.forEach(
            (element) => {
                if (!element) {return;}
                element.textContent = text;
            }
        )
    }
    if (!turn) { turn = CURRENT_TURN + 1}
    if (turn < 0 || turn >= GAME_TURNS.length) { return; }
    if (!countDownTickTime) {countDownTickTime = 1000}
    
    if (!CURRENT_TURN_ELEMENTS[0] || !CURRENT_TURN_ELEMENTS[1]) { console.error(`Current turn elements not loaded.`); return; }
    if (!CURRENT_TURN_RESULT_TEXT_ELEMENTS[0] || !CURRENT_TURN_RESULT_TEXT_ELEMENTS[1]) { console.error(`Current turn elements not loaded.`); return; }
    
    const uuid = crypto.randomUUID();
    CURRENT_ANIMATION_UUID = uuid;
    changeTurn(CURRENT_TURN); // Just in case an animation is already in progress


    CURRENT_TURN_ELEMENTS.forEach(
        (element) => {
            if (!element) {return;}
            element.textContent = "✊";
            element.style.backgroundColor = "#000000";
        }
    )

    // _focusTurnInHistory(turn);
    // ANIMATING_TOWARDS_TURN = turn;
    // _unfocusTurnInHistory(CURRENT_TURN);

    // Countdown from 3 to 0
    for (let i = 0; i < 4; i++) {
        setTimeout(
            (animation_uuid: string) => {
                if (CURRENT_ANIMATION_UUID != animation_uuid) {console.log(`Changed turn before finishing animation, ignoring animation`); return;}
                setBothTurnResultElementsTo((3 - i).toString())
            },
            i * countDownTickTime,
            uuid
        )
    }
    setTimeout(
        (expected_uuid: string) => {
            if (CURRENT_ANIMATION_UUID != expected_uuid) {console.log(`Changed turn before finishing animation, ignoring animation`); return;}
            changeTurn(turn);
            // ANIMATING_TOWARDS_TURN = null;
        },
        3 * countDownTickTime,
        uuid
    )
    
}

function _animationNextTurn() {
    if (ANIMATION_IS_PAUSED) { return; }
    animateTurn(CURRENT_TURN+1, 1000 * ANIMATION_SPEED)
    if (CURRENT_TURN + 1 >= GAME_TURNS.length) {
        document.getElementById("pause_button")!.textContent = "Play";
        return;
    }
    setTimeout(_animationNextTurn, (3000 + WAIT_BETWEEN_TURN_ANIMATION) * ANIMATION_SPEED)
}

function startAnimation() {
    if (CURRENT_TURN + 1 >= GAME_TURNS.length) {
        return;
    }
    document.getElementById("pause_button")!.textContent = "Pause";
    ANIMATION_IS_PAUSED = false;
    _animationNextTurn()
}

function pauseButtonPress(){
    if (CURRENT_TURN + 1 >= GAME_TURNS.length && ANIMATION_IS_PAUSED) {
        CURRENT_TURN = 0;
        startAnimation();
        return;
    }
    if (ANIMATION_IS_PAUSED){
        startAnimation();
    } else {
        cancelCurrentAnimation(true);
    }
}

function setReplaySpeed(speed: number) {
    console.log(`changiong speed: ${speed}`)
    if (speed < 0.1) { alert(`Replay speed ${speed} is too small. Only values >= 0.1 are allowed`)}
    const round_decimal_places = 3
    ANIMATION_SPEED = Math.round(speed * (10**round_decimal_places)) / 10**round_decimal_places;
    // @ts-ignore
    if (document.getElementById("replay_speed_input").value == speed.toString()) {
        // This function is called on input => prevent recursive calls
        return;
    }
    // @ts-ignore
    document.getElementById("replay_speed_input").value = speed.toString();
}
