"use strict";
const VALID_TURNS = ['KAMEN', 'PAPIER', 'NOZNICE', 'error'];
const TURN_EMOJI = new Map([['KAMEN', '🪨'], ['PAPIER', '📄'], ['NOZNICE', '✂️'], ['error', '⚠️']]);
let TURN_NUMBER_ELEMENTS = [];
let TURN_PAIR_ELEMENTS = [];
let CURRENT_TURN_ELEMENTS = [null, null];
let FOCUSED_TURN = -1;
let TURN = null;
let SPEED = 1;
let PAUSED = true;
let PLAYER_NAMES = [null, null];
let GAME_TURNS = [];
let FINAL_SCORE = [null, null];
let ERROR_MSG = '';
const WINNER_COLOR = '#00ff00';
const LOSER_COLOR = '#ff0000';
const DRAW_COLOR = '#ffb700';
function init() {
    let fileSelector = document.getElementById('upload_input');
    if (!fileSelector) {
        return;
    }
    fileSelector.addEventListener('change', (event) => {
        console.log('Detected file, upload, running handle_upload()');
        // @ts-ignore
        handle_upload(event?.target?.files[0]);
    });
}
function handle_upload(file) {
    console.log(`File upload: ${file.name}`);
    const reader = new FileReader();
    reader.readAsText(file);
    reader.addEventListener('load', (e) => {
        // @ts-ignore
        loadGameData(e.target.result.split('\n'));
    });
}
function validateTurn(turn) {
    return VALID_TURNS.indexOf(turn) != -1;
}
function parseGameData(data) {
    console.log(`Parsing game data...`);
    // console.log(`DEBUG LOG!`)
    if (!Array.isArray(data)) {
        ERROR_MSG = `Error in parseGameData(): data argument must an array.`;
        return null;
    }
    if (data.length < 3) {
        ERROR_MSG = `Game data too short, requires at least 3 lines.`;
        return null;
    }
    // PLAYER NAMES
    PLAYER_NAMES[0] = data[0];
    PLAYER_NAMES[1] = data[1];
    // SCORE
    let score = data[2].split(' ');
    if (score.length != 2) {
        ERROR_MSG = `Invalid score: Line 3 should contain two numbers, scores of players, got ${score}.`;
        return null;
    }
    if (isNaN(Number.parseInt(score[0]))) {
        ERROR_MSG = `Invalid score: Line 3 should contain two numbers, ${score[0]} is not a number.`;
        return null;
    }
    if (isNaN(Number.parseInt(score[1]))) {
        ERROR_MSG = `Invalid score: Line 3 should contain two numbers, ${score[1]} is not a number.`;
        return null;
    }
    FINAL_SCORE = score;
    // TURNS
    GAME_TURNS = [];
    for (let i = 3; i < data.length; i++) {
        let line = data[i].split(" ");
        if (line.length != 2) {
            if (line.length < 2) {
                ERROR_MSG = `Invalid data structure on line ${i}: Too little turns, requires 2, got ${line.length}`;
            }
            else {
                ERROR_MSG = `Invalid data structure on line ${i}: Too many turns, requires 2, got ${line.length}`;
            }
            return null;
        }
        if (!validateTurn(line[0])) {
            ERROR_MSG = `Invalid turn '${line[0]}' on line ${i}`;
            return null;
        }
        if (!validateTurn(line[1])) {
            ERROR_MSG = `Invalid turn '${line[1]}' on line ${i}`;
            return null;
        }
        GAME_TURNS.push(line);
    }
    TURN = 0;
    // console.log(`Done parsing data.`)
    return true;
}
function loadGameData(data) {
    const result = parseGameData(data);
    // console.log(`Parsedata returned: ${result}`)
    document.getElementById('replay_canvas').style.display = 'block';
    if (result == null) {
        alert(`Error parsing game data: ${ERROR_MSG}.`);
    }
    else {
        console.log(`Loaded succesfully!`);
    }
    setupTurnHistory(GAME_TURNS);
}
// console.log(parseGameData(
//     ['player1', 'player2', '0 0', 'KAMEN KAMEN']
// )&&'[DEBUG] Successfully parsed!')
// console.log(`[DEBUG] PLAYER_NAMES=${PLAYER_NAMES} GAME_TURNS=${GAME_TURNS}`)
function whoWonMatch(turn1, turn2) {
    if (!VALID_TURNS.includes(turn1) || !VALID_TURNS.includes(turn2)) {
        return 0;
    }
    // Rest of function was generated by Gemini 3.6 Flash
    if (turn1 === turn2)
        return 0;
    if (turn1 === "error")
        return 2;
    if (turn2 === "error")
        return 1;
    const WINNING_MOVES = {
        "KAMEN": "NOZNICE",
        "PAPIER": "KAMEN",
        "NOZNICE": "PAPIER"
    };
    return WINNING_MOVES[turn1] === turn2 ? 1 : 2;
}
function setupTurnHistory(turns) {
    const current_turn_element1 = document.getElementById("current_turn_p1_text");
    const current_turn_element2 = document.getElementById("current_turn_p2_text");
    CURRENT_TURN_ELEMENTS = [
        current_turn_element1 instanceof HTMLParagraphElement ? current_turn_element1 : null,
        current_turn_element2 instanceof HTMLParagraphElement ? current_turn_element2 : null,
    ];
    let turn_counter = document.getElementById("history_turn_counter");
    let history_p1 = document.getElementById("p1_history");
    let history_p2 = document.getElementById("p2_history");
    turns.forEach((turn, index) => {
        const turn_number_element = document.createElement('p');
        turn_number_element.innerText = index.toString();
        turn_counter?.appendChild(turn_number_element);
        TURN_NUMBER_ELEMENTS.push(turn_number_element);
        const winner = whoWonMatch(turn[0], turn[1]);
        const element1 = document.createElement('div');
        const element_text1 = document.createElement('p');
        const emoji1 = TURN_EMOJI.get(turn[0]) ?? 'ERROR LOADING EMOJI';
        element_text1.innerText = emoji1;
        element1.style.backgroundColor = [DRAW_COLOR, WINNER_COLOR, LOSER_COLOR][winner];
        element1.appendChild(element_text1);
        history_p1?.appendChild(element1);
        const element2 = document.createElement('div');
        const element_text2 = document.createElement('p');
        const emoji2 = TURN_EMOJI.get(turn[1]) ?? 'ERROR LOADING EMOJI';
        element_text2.innerText = emoji2;
        element2.style.backgroundColor = [DRAW_COLOR, LOSER_COLOR, WINNER_COLOR][winner];
        element2.appendChild(element_text2);
        history_p2?.appendChild(element2);
        TURN_PAIR_ELEMENTS.push([element1, element2]);
    });
    focusTurn(0);
}
function game_controls_action(action) {
    switch (action) {
        case 'pause':
            break;
        default:
            break;
    }
}
function isScrolledIntoView(elem) {
    const elemRect = elem.getBoundingClientRect();
    const container = document.getElementById("replay_canvas_history");
    if (!container) {
        console.error(`Failed to load replay_canvas_history`);
        return false;
    }
    const containerRect = container.getBoundingClientRect();
    return (elemRect.top >= containerRect.top &&
        elemRect.bottom <= containerRect.bottom &&
        elemRect.left >= containerRect.left &&
        elemRect.right <= containerRect.right);
}
function _focusScrollOnTurn(turn) {
    if (turn < 0 || turn >= TURN_NUMBER_ELEMENTS.length) {
        return;
    }
    TURN_NUMBER_ELEMENTS[turn].scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'start' });
}
function _unfocusTurn(turn) {
    if (turn < 0 || turn >= TURN_NUMBER_ELEMENTS.length) {
        return;
    }
    const turn_number_element = TURN_NUMBER_ELEMENTS[turn];
    turn_number_element.style.backgroundColor = 'black';
    turn_number_element.style.color = 'white';
}
function focusTurn(turn) {
    console.log(`FOCUS TURN ${turn}`);
    _unfocusTurn(FOCUSED_TURN);
    if (turn < 0 || turn >= TURN_NUMBER_ELEMENTS.length) {
        return;
    }
    FOCUSED_TURN = turn;
    const turn_number_element = TURN_NUMBER_ELEMENTS[turn];
    const [element1, element2] = TURN_PAIR_ELEMENTS[turn];
    turn_number_element.style.backgroundColor = 'yellow';
    turn_number_element.style.color = 'black';
    console.log(`CURRENT_TURN_ELEMENTS: ${CURRENT_TURN_ELEMENTS[0]?.textContent}`);
    if (CURRENT_TURN_ELEMENTS[0]) {
        CURRENT_TURN_ELEMENTS[0].textContent = TURN_EMOJI.get(GAME_TURNS[turn][0]) ?? "Error";
        console.log(`Set emoji to ${TURN_EMOJI.get(GAME_TURNS[turn][0]) ?? "Error"}`);
    }
    else {
        console.log(`Coundn't find current turn element 0`);
    }
    if (CURRENT_TURN_ELEMENTS[1]) {
        CURRENT_TURN_ELEMENTS[1].textContent = TURN_EMOJI.get(GAME_TURNS[turn][1]) ?? "Error";
    }
    else {
        console.log(`Coundn't find current turn element 1`);
    }
    _focusScrollOnTurn(turn);
}
function focusNextTurn() {
    console.log(`FOCUS_NEXT`);
    if (FOCUSED_TURN >= TURN_NUMBER_ELEMENTS.length - 1) {
        return;
    }
    focusTurn(FOCUSED_TURN + 1);
}
function focusPreviousTurn() {
    console.log(`FOCUS_PREVIOUS`);
    if (FOCUSED_TURN <= 0) {
        return;
    }
    focusTurn(FOCUSED_TURN - 1);
}
function DEBUGisinview() {
    console.log(`Is in view? ${isScrolledIntoView(TURN_NUMBER_ELEMENTS[17])} ${TURN_NUMBER_ELEMENTS[17].innerText}`);
}
